### ISSUE TITLE
Typo in four_iso?

### ISSUE THREAD

**Issue by Krijn-math** [KULeuven-COSIC/Radical-Isogenies#1]
On line 550 of crad_512.m the denominator is equal to `(C42-C4+1)^2`
I think this should be `(C42+C4+1)^2` in order to match formula 10 from the paper.

**Comment by TDecru** [comment]
Hey,

Both the code and the formula in the paper are correct. The reason for the misunderstanding is probably how the minus sign is being handled in the code compared to the formula in the paper. The input A (respectively newA) in the code is actually -b (respectively -b') from the paper. Notice how Conjecture 2 also talks about having to compute alpha (which is parameter C in the code) as MINUS rho to the power mu in the case p = 7 mod 8 (which is true CSURF-512 prime). However, the code says C := A^quart_exp instead.
So you need to rethink 3 minus signs, but alternatively you could rewrite the two lines of the four_iso code as follows and see that they correspond to formula (10):
  C := -A^quart_exp; C4 := 4*C; C42 := C4*C;
  newA := C*(C42+1)/(C42+C4+1)^2;
This time we indeed take minus the quartic root, then the fraction newA loses its sign (due to the factor C), but rememember that we compute newA = -b' anyway; the factor C42+1 doesn't change anything since we square C; the denominator looks really different but it's just the difference between (2C+1)^4 and (-2C+1)^4.
Sorry for the odd notation in the code, hope this clears things up a bit.

All the best,
Thomas

**Comment by Krijn-math** [comment]
Hey Thomas,
Thanks for the explanation, I had indeed missed that the input A is actually -b. All cleared up!
Cheers,
Krijn
